name: Greet Contributors

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  greet-contributor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Greet Contributor
        run: |
          echo "Hello, @$GITHUB_ACTOR! Thank you for your contribution to Pehchaan. 🌟"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
